### PR TITLE
Export protobuf headers to make #include consistent between --install and --no-install

### PR DESCRIPTION
**Pull request by mabelzhang**
Fixes https://github.com/Field-Robotics-Lab/ds_sim/pull/6#issuecomment-1017445836
Depends on / should be merged at the same time as https://github.com/Field-Robotics-Lab/ds_sim/pull/6
May or may not depend on https://github.com/Field-Robotics-Lab/dave/pull/183

This makes the `#include <*.pb.h>` line for generated protobuf messages consistent between `catkin config --install` and `--no-install`.

In addition to fixing that regression above, with https://github.com/Field-Robotics-Lab/ds_sim/pull/6 now you should be able to compile with or without the install option:
```
catkin config --install
catkin build
```

```
catkin config --no-install
catkin build
```

Previously, the compiler complained about `#include <*.pb.h>`, which had to omit the package name when you don't install, and had to include the package name when you do install.

### CODE REVIEW

**Comment by mabelzhang** [comment]
CI is failing on the line that https://github.com/Field-Robotics-Lab/ds_sim/pull/6 changes to work with this PR.
```
In file included from /tmp/uuv_ws/src/dave/ds_sim/gazebo_src/dsros_dvl.cc:42:
/tmp/uuv_ws/src/dave/ds_sim/gazebo_src/dsros_dvl.hh:60:10: fatal error: StratifiedCurrentVelocity.pb.h: No such file or directory
   60 | #include <StratifiedCurrentVelocity.pb.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Review by woensug-choi — APPROVED** [review]
Thank you for the deep dives into this. I am happy to report all my problems are solved. Now, we can really move on to catkin build!

**Comment by mabelzhang** [comment]
Merged https://github.com/Field-Robotics-Lab/ds_sim/pull/6. Rerunning checks here... Hope it passes

**Comment by mabelzhang** [comment]
Yayy! Checks passed. Thank you @woensug-choi for reviewing this series of PRs!
